//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Citrix.SelfServiceDesktops.Admin.WebApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HelpText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HelpText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Citrix.SelfServiceDesktops.Admin.WebApp.Resources.HelpText", typeof(HelpText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional Url for Agent (e.g. http://server:8000/).
        /// </summary>
        public static string AgentUriHelp {
            get {
                return ResourceManager.GetString("AgentUriHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The address of the Broker web page (WI for XenDesktop 5.6).
        /// </summary>
        public static string BrokerUriHelp {
            get {
                return ResourceManager.GetString("BrokerUriHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The address of the CloudPlatform SDK(usually of the form http://server:8080/client/api).
        /// </summary>
        public static string CloudStackUriHelp {
            get {
                return ResourceManager.GetString("CloudStackUriHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user friendly description of the desktop offering.
        /// </summary>
        public static string DescriptionHelp {
            get {
                return ResourceManager.GetString("DescriptionHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the PVS device collection (only required for PVS desktops).
        /// </summary>
        public static string DeviceCollectionNameHelp {
            get {
                return ResourceManager.GetString("DeviceCollectionNameHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address or FQDN of the PVS server (only required for PVS desktops).
        /// </summary>
        public static string DeviceCollectionServerHelp {
            get {
                return ResourceManager.GetString("DeviceCollectionServerHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the PVS Site (only required for PVS desktops).
        /// </summary>
        public static string DeviceCollectionSiteHelp {
            get {
                return ResourceManager.GetString("DeviceCollectionSiteHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The GUID of the CloudPlatform dsik offering to be used (only required forPVS desktop booting from ISO).
        /// </summary>
        public static string DiskOfferingIdHelp {
            get {
                return ResourceManager.GetString("DiskOfferingIdHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional CloudPlatform domain for user login.
        /// </summary>
        public static string DomainHelp {
            get {
                return ResourceManager.GetString("DomainHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix for generating hostnames for this desktop group (max 11 characters).
        /// </summary>
        public static string HostnamePrefixHelp {
            get {
                return ResourceManager.GetString("HostnamePrefixHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The hypervisor to use. Only required if booting PVS desktop from ISO.
        /// </summary>
        public static string HypervisorHelp {
            get {
                return ResourceManager.GetString("HypervisorHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The GUID of the CloudPatform ISO to use (only required for PVS desktop offerings).
        /// </summary>
        public static string IsoIdHelp {
            get {
                return ResourceManager.GetString("IsoIdHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The port on which  that the Self Service Desktop agent listens for connections from the web app..
        /// </summary>
        public static string ListenPortHelp {
            get {
                return ResourceManager.GetString("ListenPortHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A name for the desktop offering.
        /// </summary>
        public static string NameHelp {
            get {
                return ResourceManager.GetString("NameHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CloudPlatform network id (GUID).
        /// </summary>
        public static string NetworkIdHelp {
            get {
                return ResourceManager.GetString("NetworkIdHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether the PowerShell script should write debug log entries.
        /// </summary>
        public static string PowerShellScriptDebugHelp {
            get {
                return ResourceManager.GetString("PowerShellScriptDebugHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freqency at which the PowerShell script will execute..
        /// </summary>
        public static string PowerShellScriptFrequencyHelp {
            get {
                return ResourceManager.GetString("PowerShellScriptFrequencyHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the powershell script executed by the Self Service Desktops Agent.
        /// </summary>
        public static string PowerShellScriptPathHelp {
            get {
                return ResourceManager.GetString("PowerShellScriptPathHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The GUID of the CloudPlatform service offering to be used for desktops .
        /// </summary>
        public static string ServiceOfferingIdHelp {
            get {
                return ResourceManager.GetString("ServiceOfferingIdHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether this Self Service Dektop Agent is responsible for managing/synchonizing this device collection (allows you to manually load balance multiple Self Service Desktop Agents).
        /// </summary>
        public static string SyncHelp {
            get {
                return ResourceManager.GetString("SyncHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The GUID of the CloudPlatform template to boot from (not required for PVS desktop offerings that boot from ISO).
        /// </summary>
        public static string TemplateIdHelp {
            get {
                return ResourceManager.GetString("TemplateIdHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CloudPlatform zone id (GUID).
        /// </summary>
        public static string ZoneIdHelp {
            get {
                return ResourceManager.GetString("ZoneIdHelp", resourceCulture);
            }
        }
    }
}
